basePath: /api
definitions:
  model.Jwt:
    properties:
      ExpiresAt:
        type: string
      createdAt:
        type: string
      id:
        type: integer
      token:
        type: string
      updatedAt:
        type: string
    type: object
  model.Ou:
    properties:
      createdAt:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      pid:
        type: integer
      updatedAt:
        type: string
    type: object
  model.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      headerImg:
        type: string
      id:
        type: integer
      name:
        type: string
      ou_id:
        type: integer
      status:
        type: integer
      updatedAt:
        type: string
    type: object
  request.LoginForm:
    properties:
      name:
        type: string
      password:
        type: string
    type: object
  result.PageResult:
    properties:
      list: {}
      page:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
info:
  contact: {}
  description: This is a sample Server pets
  title: Swagger Example API
  version: 0.0.1
paths:
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名和密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.LoginForm'
      produces:
      - application/json
      responses:
        "200":
          description: jwt token
          schema:
            $ref: '#/definitions/model.Jwt'
      summary: 用户登录
      tags:
      - apiPublic
  /ous:
    get:
      consumes:
      - application/json
      parameters:
      - description: 当前页码
        in: query
        name: page
        type: string
      - description: 每页显示条数
        in: query
        name: size
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 部门列表
          schema:
            allOf:
            - $ref: '#/definitions/result.PageResult'
            - properties:
                list:
                  items:
                    $ref: '#/definitions/model.Ou'
                  type: array
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取部门列表
      tags:
      - apiOu
    post:
      consumes:
      - application/json
      parameters:
      - description: 部门信息
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Ou'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/model.Ou'
      security:
      - ApiKeyAuth: []
      summary: 创建部门
      tags:
      - apiOu
  /ous/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 部门id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/model.Ou'
      security:
      - ApiKeyAuth: []
      summary: 删除部门
      tags:
      - apiOu
    get:
      consumes:
      - application/json
      parameters:
      - description: 部门id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/model.Ou'
      security:
      - ApiKeyAuth: []
      summary: 获取部门详情
      tags:
      - apiOu
    put:
      consumes:
      - application/json
      parameters:
      - description: 部门id
        in: path
        name: id
        required: true
        type: string
      - description: 部门信息
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Ou'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/model.Ou'
      security:
      - ApiKeyAuth: []
      summary: 更新部门
      tags:
      - apiOu
  /register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: 用户详情
          schema:
            $ref: '#/definitions/model.User'
      summary: 用户注册
      tags:
      - apiPublic
  /users:
    get:
      consumes:
      - application/json
      parameters:
      - description: 当前页码
        in: query
        name: page
        type: string
      - description: 每页显示条数
        in: query
        name: size
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 用户列表
          schema:
            allOf:
            - $ref: '#/definitions/result.PageResult'
            - properties:
                list:
                  items:
                    $ref: '#/definitions/model.Ou'
                  type: array
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取用户列表
      tags:
      - apiUser
    post:
      consumes:
      - application/json
      parameters:
      - description: 要创建的用户信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: 用户详情
          schema:
            $ref: '#/definitions/model.User'
      security:
      - ApiKeyAuth: []
      summary: 创建用户
      tags:
      - apiUser
  /users/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 用户详情
          schema:
            $ref: '#/definitions/model.User'
      security:
      - ApiKeyAuth: []
      summary: 删除用户
      tags:
      - apiUser
    get:
      consumes:
      - application/json
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 用户详情
          schema:
            $ref: '#/definitions/model.User'
      security:
      - ApiKeyAuth: []
      summary: 获取用户详情
      tags:
      - apiUser
    post:
      consumes:
      - application/json
      parameters:
      - description: 要修改的用户信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "200":
          description: 用户详情
          schema:
            $ref: '#/definitions/model.User'
      security:
      - ApiKeyAuth: []
      summary: 更新用户
      tags:
      - apiUser
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
